# Form implementation generated from reading ui file '/home/viblab/_developments_/Projects/General_Projects/VALE_DataGUI/Desktop/DataGUI/ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.grpDataPlot = QtWidgets.QGroupBox(parent=self.centralWidget)
        self.grpDataPlot.setGeometry(QtCore.QRect(10, 150, 981, 361))
        self.grpDataPlot.setStyleSheet("QGroupBox { \n"
"     border: 2px solid gray; \n"
"     border-radius: 3px; \n"
" } ")
        self.grpDataPlot.setObjectName("grpDataPlot")
        self.frmDataPlot = QtWidgets.QFrame(parent=self.grpDataPlot)
        self.frmDataPlot.setGeometry(QtCore.QRect(10, 20, 961, 331))
        self.frmDataPlot.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frmDataPlot.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frmDataPlot.setObjectName("frmDataPlot")
        self.grpDataAnalysis = QtWidgets.QGroupBox(parent=self.centralWidget)
        self.grpDataAnalysis.setGeometry(QtCore.QRect(10, 520, 981, 211))
        self.grpDataAnalysis.setStyleSheet("QGroupBox { \n"
"     border: 2px solid gray; \n"
"     border-radius: 3px; \n"
" } ")
        self.grpDataAnalysis.setFlat(False)
        self.grpDataAnalysis.setObjectName("grpDataAnalysis")
        self.grpDataSource = QtWidgets.QGroupBox(parent=self.centralWidget)
        self.grpDataSource.setGeometry(QtCore.QRect(10, 10, 981, 131))
        self.grpDataSource.setStyleSheet("QGroupBox { \n"
"     border: 2px solid gray; \n"
"     border-radius: 3px; \n"
" } ")
        self.grpDataSource.setObjectName("grpDataSource")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(parent=self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutQt = QtGui.QAction(parent=MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionAboutPython = QtGui.QAction(parent=MainWindow)
        self.actionAboutPython.setObjectName("actionAboutPython")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionAboutQt)
        self.menuAbout.addAction(self.actionAboutPython)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.grpDataPlot.setTitle(_translate("MainWindow", "Data Plot"))
        self.grpDataAnalysis.setTitle(_translate("MainWindow", "Data Analysis"))
        self.grpDataSource.setTitle(_translate("MainWindow", "Data Source"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAboutQt.setText(_translate("MainWindow", "About Qt"))
        self.actionAboutPython.setText(_translate("MainWindow", "About Python"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
